// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZt1AqfnhAKa8OKbdc1DccbPDYCEl8mR4',
    appId: '1:1033308085977:web:ce8b38d17fce83d13428c8',
    messagingSenderId: '1033308085977',
    projectId: 'polmaps',
    authDomain: 'polmaps.firebaseapp.com',
    storageBucket: 'polmaps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSdjuYW5GNQUh7mREcHuVSaqZ14d6PiuA',
    appId: '1:1033308085977:android:86f714dd472f4be93428c8',
    messagingSenderId: '1033308085977',
    projectId: 'polmaps',
    storageBucket: 'polmaps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZy7KXALH9i34yWRhSF7uNeNnXhAfzsRc',
    appId: '1:1033308085977:ios:aa2a49819e440f333428c8',
    messagingSenderId: '1033308085977',
    projectId: 'polmaps',
    storageBucket: 'polmaps.appspot.com',
    iosBundleId: 'ru.polbanki.onegid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZy7KXALH9i34yWRhSF7uNeNnXhAfzsRc',
    appId: '1:1033308085977:ios:aa2a49819e440f333428c8',
    messagingSenderId: '1033308085977',
    projectId: 'polmaps',
    storageBucket: 'polmaps.appspot.com',
    iosBundleId: 'ru.polbanki.onegid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZt1AqfnhAKa8OKbdc1DccbPDYCEl8mR4',
    appId: '1:1033308085977:web:54874b5c65c56a6e3428c8',
    messagingSenderId: '1033308085977',
    projectId: 'polmaps',
    authDomain: 'polmaps.firebaseapp.com',
    storageBucket: 'polmaps.appspot.com',
  );
}
