platform :ios, '13.0'
inhibit_all_warnings!

target 'Runner' do
  pod 'ObjectiveSugar', '~> 0.5'

  target 'RunnerTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 2.0.1'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
  
      end
        installer.generated_projects.each do |project|
            project.targets.each do |target|
                    target.build_configurations.each do |config|
                        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
                    end
                end
            end
      end